services:
  produtos:
    build: ./produto
    ports:
      - "3001:3001"

  pedidos:
    build: ./pedido
    ports:
      - "3002:3002"
    environment:
      PRODUTOS_URL: http://produtos:3001
    depends_on:
      - produtos