services:
  produto:
    build: ./produto
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/produtos_db
    depends_on:
      postgres:
        condition: service_healthy

  pedido:
    build: ./pedido
    ports:
      - "3002:3002"
    environment:
      PRODUTOS_URL: http://produto:3001
      CLIENTES_URL: http://clientes:3003
    depends_on:
      - produto
      - clientes

  clientes:
    build: ./clientes
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/clientes_db
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    environment:
      PRODUTOS_URL: http://produto:3001
      PEDIDOS_URL: http://pedido:3002
      CLIENTES_URL: http://clientes:3003
    depends_on:
      - produto
      - pedido
      - clientes

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produtos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./banco/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d produtos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
